apiVersion: v1
kind: Service
metadata:
  name: mi-nginx-service
spec:
  selector:
    app: mi-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # O LoadBalancer si tienes configurado

