apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-nginx
  template:
    metadata:
      labels:
        app: mi-nginx
    spec:
      containers:
        - name: mi-nginx
          image: mi-nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          configMap:
            name: mi-html

